//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DataModel", "FK_DataObjects_UserProfiles", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.Models.UserProfile), "DataObject", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.Models.DataObject), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_DataObjectTags_DataObjects", "DataObject", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.Models.DataObject), "DataObjectTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.Models.DataObjectTag), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_SupportRequests_UserProfiles", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.Models.UserProfile), "SupportRequest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.Models.SupportRequest), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_ToolObjects_UserProfiles", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.Models.UserProfile), "ToolObject", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.Models.ToolObject), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_ToolObjectTags_ToolObjects", "ToolObject", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.Models.ToolObject), "ToolObjectTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.Models.ToolObjectTag), true)]

#endregion

namespace Server.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TauEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TauEntities object using the connection string found in the 'TauEntities' section of the application configuration file.
        /// </summary>
        public TauEntities() : base("name=TauEntities", "TauEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TauEntities object.
        /// </summary>
        public TauEntities(string connectionString) : base(connectionString, "TauEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TauEntities object.
        /// </summary>
        public TauEntities(EntityConnection connection) : base(connection, "TauEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataObject> DataObjects
        {
            get
            {
                if ((_DataObjects == null))
                {
                    _DataObjects = base.CreateObjectSet<DataObject>("DataObjects");
                }
                return _DataObjects;
            }
        }
        private ObjectSet<DataObject> _DataObjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataObjectTag> DataObjectTags
        {
            get
            {
                if ((_DataObjectTags == null))
                {
                    _DataObjectTags = base.CreateObjectSet<DataObjectTag>("DataObjectTags");
                }
                return _DataObjectTags;
            }
        }
        private ObjectSet<DataObjectTag> _DataObjectTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SupportRequest> SupportRequests
        {
            get
            {
                if ((_SupportRequests == null))
                {
                    _SupportRequests = base.CreateObjectSet<SupportRequest>("SupportRequests");
                }
                return _SupportRequests;
            }
        }
        private ObjectSet<SupportRequest> _SupportRequests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ToolObject> ToolObjects
        {
            get
            {
                if ((_ToolObjects == null))
                {
                    _ToolObjects = base.CreateObjectSet<ToolObject>("ToolObjects");
                }
                return _ToolObjects;
            }
        }
        private ObjectSet<ToolObject> _ToolObjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ToolObjectTag> ToolObjectTags
        {
            get
            {
                if ((_ToolObjectTags == null))
                {
                    _ToolObjectTags = base.CreateObjectSet<ToolObjectTag>("ToolObjectTags");
                }
                return _ToolObjectTags;
            }
        }
        private ObjectSet<ToolObjectTag> _ToolObjectTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserProfile> UserProfiles
        {
            get
            {
                if ((_UserProfiles == null))
                {
                    _UserProfiles = base.CreateObjectSet<UserProfile>("UserProfiles");
                }
                return _UserProfiles;
            }
        }
        private ObjectSet<UserProfile> _UserProfiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViolationReportItem> ViolationReportItems
        {
            get
            {
                if ((_ViolationReportItems == null))
                {
                    _ViolationReportItems = base.CreateObjectSet<ViolationReportItem>("ViolationReportItems");
                }
                return _ViolationReportItems;
            }
        }
        private ObjectSet<ViolationReportItem> _ViolationReportItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DocumentationItem> DocumentationItems
        {
            get
            {
                if ((_DocumentationItems == null))
                {
                    _DocumentationItems = base.CreateObjectSet<DocumentationItem>("DocumentationItems");
                }
                return _DocumentationItems;
            }
        }
        private ObjectSet<DocumentationItem> _DocumentationItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataObjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataObjects(DataObject dataObject)
        {
            base.AddObject("DataObjects", dataObject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataObjectTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataObjectTags(DataObjectTag dataObjectTag)
        {
            base.AddObject("DataObjectTags", dataObjectTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SupportRequests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSupportRequests(SupportRequest supportRequest)
        {
            base.AddObject("SupportRequests", supportRequest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ToolObjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToolObjects(ToolObject toolObject)
        {
            base.AddObject("ToolObjects", toolObject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ToolObjectTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToolObjectTags(ToolObjectTag toolObjectTag)
        {
            base.AddObject("ToolObjectTags", toolObjectTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserProfiles(UserProfile userProfile)
        {
            base.AddObject("UserProfiles", userProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViolationReportItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViolationReportItems(ViolationReportItem violationReportItem)
        {
            base.AddObject("ViolationReportItems", violationReportItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DocumentationItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocumentationItems(DocumentationItem documentationItem)
        {
            base.AddObject("DocumentationItems", documentationItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="DataObject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataObject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataObject object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="isPublic">Initial value of the IsPublic property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        public static DataObject CreateDataObject(global::System.Int64 id, global::System.Int32 userProfileId, global::System.DateTime created, global::System.Boolean isPublic, global::System.String title, global::System.String data)
        {
            DataObject dataObject = new DataObject();
            dataObject.Id = id;
            dataObject.UserProfileId = userProfileId;
            dataObject.Created = created;
            dataObject.IsPublic = isPublic;
            dataObject.Title = title;
            dataObject.Data = data;
            return dataObject;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ToolId
        {
            get
            {
                return _ToolId;
            }
            set
            {
                OnToolIdChanging(value);
                ReportPropertyChanging("ToolId");
                _ToolId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToolId");
                OnToolIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ToolId;
        partial void OnToolIdChanging(Nullable<global::System.Int64> value);
        partial void OnToolIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                OnUserProfileIdChanging(value);
                ReportPropertyChanging("UserProfileId");
                _UserProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserProfileId");
                OnUserProfileIdChanged();
            }
        }
        private global::System.Int32 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int32 value);
        partial void OnUserProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPublic
        {
            get
            {
                return _IsPublic;
            }
            set
            {
                OnIsPublicChanging(value);
                ReportPropertyChanging("IsPublic");
                _IsPublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublic");
                OnIsPublicChanged();
            }
        }
        private global::System.Boolean _IsPublic;
        partial void OnIsPublicChanging(global::System.Boolean value);
        partial void OnIsPublicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_DataObjects_UserProfiles", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_DataObjects_UserProfiles", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_DataObjects_UserProfiles", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_DataObjects_UserProfiles", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("DataModel.FK_DataObjects_UserProfiles", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_DataObjectTags_DataObjects", "DataObjectTag")]
        public EntityCollection<DataObjectTag> DataObjectTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DataObjectTag>("DataModel.FK_DataObjectTags_DataObjects", "DataObjectTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DataObjectTag>("DataModel.FK_DataObjectTags_DataObjects", "DataObjectTag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="DataObjectTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataObjectTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataObjectTag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dataObjectId">Initial value of the DataObjectId property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static DataObjectTag CreateDataObjectTag(global::System.Int64 id, global::System.Int64 dataObjectId, global::System.String value)
        {
            DataObjectTag dataObjectTag = new DataObjectTag();
            dataObjectTag.Id = id;
            dataObjectTag.DataObjectId = dataObjectId;
            dataObjectTag.Value = value;
            return dataObjectTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DataObjectId
        {
            get
            {
                return _DataObjectId;
            }
            set
            {
                OnDataObjectIdChanging(value);
                ReportPropertyChanging("DataObjectId");
                _DataObjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataObjectId");
                OnDataObjectIdChanged();
            }
        }
        private global::System.Int64 _DataObjectId;
        partial void OnDataObjectIdChanging(global::System.Int64 value);
        partial void OnDataObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_DataObjectTags_DataObjects", "DataObject")]
        public DataObject DataObject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataObject>("DataModel.FK_DataObjectTags_DataObjects", "DataObject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataObject>("DataModel.FK_DataObjectTags_DataObjects", "DataObject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DataObject> DataObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DataObject>("DataModel.FK_DataObjectTags_DataObjects", "DataObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DataObject>("DataModel.FK_DataObjectTags_DataObjects", "DataObject", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="DocumentationItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DocumentationItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DocumentationItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isStatic">Initial value of the IsStatic property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        public static DocumentationItem CreateDocumentationItem(global::System.Int32 id, global::System.String category, global::System.String name, global::System.Boolean isStatic, global::System.String body)
        {
            DocumentationItem documentationItem = new DocumentationItem();
            documentationItem.Id = id;
            documentationItem.Category = category;
            documentationItem.Name = name;
            documentationItem.IsStatic = isStatic;
            documentationItem.Body = body;
            return documentationItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Object
        {
            get
            {
                return _Object;
            }
            set
            {
                OnObjectChanging(value);
                ReportPropertyChanging("Object");
                _Object = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Object");
                OnObjectChanged();
            }
        }
        private global::System.String _Object;
        partial void OnObjectChanging(global::System.String value);
        partial void OnObjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsStatic
        {
            get
            {
                return _IsStatic;
            }
            set
            {
                OnIsStaticChanging(value);
                ReportPropertyChanging("IsStatic");
                _IsStatic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsStatic");
                OnIsStaticChanged();
            }
        }
        private global::System.Boolean _IsStatic;
        partial void OnIsStaticChanging(global::System.Boolean value);
        partial void OnIsStaticChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="SupportRequest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SupportRequest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SupportRequest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="problem">Initial value of the Problem property.</param>
        /// <param name="solution">Initial value of the Solution property.</param>
        /// <param name="weKnowAboutIt">Initial value of the WeKnowAboutIt property.</param>
        /// <param name="weSolvedIt">Initial value of the WeSolvedIt property.</param>
        public static SupportRequest CreateSupportRequest(global::System.Int64 id, global::System.Int32 userProfileId, global::System.DateTime created, global::System.String title, global::System.String problem, global::System.String solution, global::System.Boolean weKnowAboutIt, global::System.Boolean weSolvedIt)
        {
            SupportRequest supportRequest = new SupportRequest();
            supportRequest.Id = id;
            supportRequest.UserProfileId = userProfileId;
            supportRequest.Created = created;
            supportRequest.Title = title;
            supportRequest.Problem = problem;
            supportRequest.Solution = solution;
            supportRequest.WeKnowAboutIt = weKnowAboutIt;
            supportRequest.WeSolvedIt = weSolvedIt;
            return supportRequest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                OnUserProfileIdChanging(value);
                ReportPropertyChanging("UserProfileId");
                _UserProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserProfileId");
                OnUserProfileIdChanged();
            }
        }
        private global::System.Int32 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int32 value);
        partial void OnUserProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Problem
        {
            get
            {
                return _Problem;
            }
            set
            {
                OnProblemChanging(value);
                ReportPropertyChanging("Problem");
                _Problem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Problem");
                OnProblemChanged();
            }
        }
        private global::System.String _Problem;
        partial void OnProblemChanging(global::System.String value);
        partial void OnProblemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Solution
        {
            get
            {
                return _Solution;
            }
            set
            {
                OnSolutionChanging(value);
                ReportPropertyChanging("Solution");
                _Solution = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Solution");
                OnSolutionChanged();
            }
        }
        private global::System.String _Solution;
        partial void OnSolutionChanging(global::System.String value);
        partial void OnSolutionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WeKnowAboutIt
        {
            get
            {
                return _WeKnowAboutIt;
            }
            set
            {
                OnWeKnowAboutItChanging(value);
                ReportPropertyChanging("WeKnowAboutIt");
                _WeKnowAboutIt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeKnowAboutIt");
                OnWeKnowAboutItChanged();
            }
        }
        private global::System.Boolean _WeKnowAboutIt;
        partial void OnWeKnowAboutItChanging(global::System.Boolean value);
        partial void OnWeKnowAboutItChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WeSolvedIt
        {
            get
            {
                return _WeSolvedIt;
            }
            set
            {
                OnWeSolvedItChanging(value);
                ReportPropertyChanging("WeSolvedIt");
                _WeSolvedIt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeSolvedIt");
                OnWeSolvedItChanged();
            }
        }
        private global::System.Boolean _WeSolvedIt;
        partial void OnWeSolvedItChanging(global::System.Boolean value);
        partial void OnWeSolvedItChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_SupportRequests_UserProfiles", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_SupportRequests_UserProfiles", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_SupportRequests_UserProfiles", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_SupportRequests_UserProfiles", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("DataModel.FK_SupportRequests_UserProfiles", "UserProfile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="ToolObject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ToolObject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ToolObject object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="isPublic">Initial value of the IsPublic property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="tool">Initial value of the Tool property.</param>
        public static ToolObject CreateToolObject(global::System.Int64 id, global::System.Int32 userProfileId, global::System.DateTime created, global::System.Boolean isPublic, global::System.String title, global::System.String tool)
        {
            ToolObject toolObject = new ToolObject();
            toolObject.Id = id;
            toolObject.UserProfileId = userProfileId;
            toolObject.Created = created;
            toolObject.IsPublic = isPublic;
            toolObject.Title = title;
            toolObject.Tool = tool;
            return toolObject;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int64> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                OnUserProfileIdChanging(value);
                ReportPropertyChanging("UserProfileId");
                _UserProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserProfileId");
                OnUserProfileIdChanged();
            }
        }
        private global::System.Int32 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int32 value);
        partial void OnUserProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPublic
        {
            get
            {
                return _IsPublic;
            }
            set
            {
                OnIsPublicChanging(value);
                ReportPropertyChanging("IsPublic");
                _IsPublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublic");
                OnIsPublicChanged();
            }
        }
        private global::System.Boolean _IsPublic;
        partial void OnIsPublicChanging(global::System.Boolean value);
        partial void OnIsPublicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tool
        {
            get
            {
                return _Tool;
            }
            set
            {
                OnToolChanging(value);
                ReportPropertyChanging("Tool");
                _Tool = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tool");
                OnToolChanged();
            }
        }
        private global::System.String _Tool;
        partial void OnToolChanging(global::System.String value);
        partial void OnToolChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_ToolObjects_UserProfiles", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_ToolObjects_UserProfiles", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_ToolObjects_UserProfiles", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DataModel.FK_ToolObjects_UserProfiles", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("DataModel.FK_ToolObjects_UserProfiles", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_ToolObjectTags_ToolObjects", "ToolObjectTag")]
        public EntityCollection<ToolObjectTag> ToolObjectTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ToolObjectTag>("DataModel.FK_ToolObjectTags_ToolObjects", "ToolObjectTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ToolObjectTag>("DataModel.FK_ToolObjectTags_ToolObjects", "ToolObjectTag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="ToolObjectTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ToolObjectTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ToolObjectTag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="toolObjectId">Initial value of the ToolObjectId property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static ToolObjectTag CreateToolObjectTag(global::System.Int64 id, global::System.Int64 toolObjectId, global::System.String value)
        {
            ToolObjectTag toolObjectTag = new ToolObjectTag();
            toolObjectTag.Id = id;
            toolObjectTag.ToolObjectId = toolObjectId;
            toolObjectTag.Value = value;
            return toolObjectTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ToolObjectId
        {
            get
            {
                return _ToolObjectId;
            }
            set
            {
                OnToolObjectIdChanging(value);
                ReportPropertyChanging("ToolObjectId");
                _ToolObjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToolObjectId");
                OnToolObjectIdChanged();
            }
        }
        private global::System.Int64 _ToolObjectId;
        partial void OnToolObjectIdChanging(global::System.Int64 value);
        partial void OnToolObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_ToolObjectTags_ToolObjects", "ToolObject")]
        public ToolObject ToolObject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ToolObject>("DataModel.FK_ToolObjectTags_ToolObjects", "ToolObject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ToolObject>("DataModel.FK_ToolObjectTags_ToolObjects", "ToolObject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ToolObject> ToolObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ToolObject>("DataModel.FK_ToolObjectTags_ToolObjects", "ToolObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ToolObject>("DataModel.FK_ToolObjectTags_ToolObjects", "ToolObject", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserProfile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="coverage">Initial value of the Coverage property.</param>
        /// <param name="coverageUntil">Initial value of the CoverageUntil property.</param>
        /// <param name="useGravatar">Initial value of the UseGravatar property.</param>
        /// <param name="allowContact">Initial value of the AllowContact property.</param>
        /// <param name="aPIKey">Initial value of the APIKey property.</param>
        public static UserProfile CreateUserProfile(global::System.Int32 id, global::System.String user, global::System.Byte coverage, global::System.DateTime coverageUntil, global::System.Boolean useGravatar, global::System.Boolean allowContact, global::System.Guid aPIKey)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.Id = id;
            userProfile.User = user;
            userProfile.Coverage = coverage;
            userProfile.CoverageUntil = coverageUntil;
            userProfile.UseGravatar = useGravatar;
            userProfile.AllowContact = allowContact;
            userProfile.APIKey = aPIKey;
            return userProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Coverage
        {
            get
            {
                return _Coverage;
            }
            set
            {
                OnCoverageChanging(value);
                ReportPropertyChanging("Coverage");
                _Coverage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Coverage");
                OnCoverageChanged();
            }
        }
        private global::System.Byte _Coverage;
        partial void OnCoverageChanging(global::System.Byte value);
        partial void OnCoverageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CoverageUntil
        {
            get
            {
                return _CoverageUntil;
            }
            set
            {
                OnCoverageUntilChanging(value);
                ReportPropertyChanging("CoverageUntil");
                _CoverageUntil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoverageUntil");
                OnCoverageUntilChanged();
            }
        }
        private global::System.DateTime _CoverageUntil;
        partial void OnCoverageUntilChanging(global::System.DateTime value);
        partial void OnCoverageUntilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseGravatar
        {
            get
            {
                return _UseGravatar;
            }
            set
            {
                OnUseGravatarChanging(value);
                ReportPropertyChanging("UseGravatar");
                _UseGravatar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UseGravatar");
                OnUseGravatarChanged();
            }
        }
        private global::System.Boolean _UseGravatar;
        partial void OnUseGravatarChanging(global::System.Boolean value);
        partial void OnUseGravatarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllowContact
        {
            get
            {
                return _AllowContact;
            }
            set
            {
                OnAllowContactChanging(value);
                ReportPropertyChanging("AllowContact");
                _AllowContact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowContact");
                OnAllowContactChanged();
            }
        }
        private global::System.Boolean _AllowContact;
        partial void OnAllowContactChanging(global::System.Boolean value);
        partial void OnAllowContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid APIKey
        {
            get
            {
                return _APIKey;
            }
            set
            {
                OnAPIKeyChanging(value);
                ReportPropertyChanging("APIKey");
                _APIKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("APIKey");
                OnAPIKeyChanged();
            }
        }
        private global::System.Guid _APIKey;
        partial void OnAPIKeyChanging(global::System.Guid value);
        partial void OnAPIKeyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_DataObjects_UserProfiles", "DataObject")]
        public EntityCollection<DataObject> DataObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DataObject>("DataModel.FK_DataObjects_UserProfiles", "DataObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DataObject>("DataModel.FK_DataObjects_UserProfiles", "DataObject", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_SupportRequests_UserProfiles", "SupportRequest")]
        public EntityCollection<SupportRequest> SupportRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SupportRequest>("DataModel.FK_SupportRequests_UserProfiles", "SupportRequest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SupportRequest>("DataModel.FK_SupportRequests_UserProfiles", "SupportRequest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_ToolObjects_UserProfiles", "ToolObject")]
        public EntityCollection<ToolObject> ToolObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ToolObject>("DataModel.FK_ToolObjects_UserProfiles", "ToolObject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ToolObject>("DataModel.FK_ToolObjects_UserProfiles", "ToolObject", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="ViolationReportItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViolationReportItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViolationReportItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dataId">Initial value of the DataId property.</param>
        /// <param name="toolId">Initial value of the ToolId property.</param>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        public static ViolationReportItem CreateViolationReportItem(global::System.Int32 id, global::System.Int64 dataId, global::System.Int64 toolId, global::System.Int32 userProfileId)
        {
            ViolationReportItem violationReportItem = new ViolationReportItem();
            violationReportItem.Id = id;
            violationReportItem.DataId = dataId;
            violationReportItem.ToolId = toolId;
            violationReportItem.UserProfileId = userProfileId;
            return violationReportItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DataId
        {
            get
            {
                return _DataId;
            }
            set
            {
                OnDataIdChanging(value);
                ReportPropertyChanging("DataId");
                _DataId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataId");
                OnDataIdChanged();
            }
        }
        private global::System.Int64 _DataId;
        partial void OnDataIdChanging(global::System.Int64 value);
        partial void OnDataIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ToolId
        {
            get
            {
                return _ToolId;
            }
            set
            {
                OnToolIdChanging(value);
                ReportPropertyChanging("ToolId");
                _ToolId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToolId");
                OnToolIdChanged();
            }
        }
        private global::System.Int64 _ToolId;
        partial void OnToolIdChanging(global::System.Int64 value);
        partial void OnToolIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                OnUserProfileIdChanging(value);
                ReportPropertyChanging("UserProfileId");
                _UserProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserProfileId");
                OnUserProfileIdChanged();
            }
        }
        private global::System.Int32 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int32 value);
        partial void OnUserProfileIdChanged();

        #endregion
    
    }

    #endregion
    
}
